=== AaltoAsia/O-MI/O-MI Node/src/main/resources/odf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 (x64) (http://www.altova.com) by Kary FrÃ¤mling (Aalto University) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.opengroup.org/xsd/odf/1.0/" targetNamespace="http://www.opengroup.org/xsd/odf/1.0/" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:element name="Objects" type="ObjectsType">
		<xs:annotation>
			<xs:documentation>Data Model Root Element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="ObjectsType">
		<xs:sequence>
			<xs:element name="Object" type="ObjectType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="version" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Schema version used.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ObjectType">
		<xs:sequence>
			<xs:element name="id" type="QlmIDType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="description" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="InfoItem" type="InfoItemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Object" type="ObjectType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="optional"/>
		<xs:anyAttribute>
			<xs:annotation>
				<xs:documentation>Proprietary or extended attributes.</xs:documentation>
			</xs:annotation>
		</xs:anyAttribute>
	</xs:complexType>
	<xs:complexType name="InfoItemType">
		<xs:sequence>
			<xs:element name="name" type="QlmIDType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Optional list of other names for the same InfoItem.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="description" type="DescriptionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="MetaData" type="MetaDataType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Meta-data about the InfoItem, such as "latency", "unit" etc.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="value" type="ValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Name of InfoItem, such as "PowerConsumption", "Diameter" or similar.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:anyAttribute>
			<xs:annotation>
				<xs:documentation>Proprietary or extended attributes.</xs:documentation>
			</xs:annotation>
		</xs:anyAttribute>
	</xs:complexType>
	<xs:complexType name="MetaDataType">
		<xs:sequence>
			<xs:element name="InfoItem" type="InfoItemType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DescriptionType">
		<xs:annotation>
			<xs:documentation>String with some"human-readable" text.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="lang" type="xs:string" use="optional">
					<xs:annotation>
						<xs:documentation>Language of "description" text.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:anyAttribute>
					<xs:annotation>
						<xs:documentation>Proprietary or extended attributes.</xs:documentation>
					</xs:annotation>
				</xs:anyAttribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="QlmIDType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="idType" type="xs:string" use="optional">
					<xs:annotation>
						<xs:documentation>Text identifying the ID schema.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="tagType" type="xs:string" use="optional">
					<xs:annotation>
						<xs:documentation>Text identifying the ID Tag media type. </xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="startDate" type="xs:dateTime" use="optional">
					<xs:annotation>
						<xs:documentation>Start of validity for the ID</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="endDate" type="xs:dateTime" use="optional">
					<xs:annotation>
						<xs:documentation>End of validity for the ID</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:anyAttribute>
					<xs:annotation>
						<xs:documentation>Proprietary attributes.</xs:documentation>
					</xs:annotation>
				</xs:anyAttribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="ValueType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" use="optional" default="xs:string">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="dateTime" type="xs:dateTime" use="optional"/>
				<xs:attribute name="unixTime" type="xs:long" use="optional"/>
				<xs:anyAttribute/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== AaltoAsia/O-MI/configs/SmartHouse.xml
<?xml version="1.0"?>
<!--
  Copyright (c) 2015 Aalto University.

  Licensed under the 4-clause BSD (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at top most directory of project.

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<Objects xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengroup.org/xsd/odf/1.0/" xs:schemaLocation="odf.xsd odf.xsd">
  <Object>
    <id>SmartHouse</id>
    <InfoItem name="FrontDoor">
      <value>1</value>
    </InfoItem>
    <InfoItem name="BackDoor">
      <value>1</value>
    </InfoItem>
    <Object>
      <id>Kitchen</id>
      <InfoItem name="Temperature">
        <MetaData>
          <InfoItem name="Latency">
            <value type="xs:double">2.3</value>
          </InfoItem>
          <InfoItem name="Accuracy">
            <value type="xs:double">0.05</value>
          </InfoItem>
        </MetaData>
        <value>22.3</value>
      </InfoItem>
      <InfoItem name="Moisture">
        <MetaData>
          <InfoItem name="Latency">
            <value type="xs:double">2.3</value>
          </InfoItem>
          <InfoItem name="Accuracy">
            <value type="xs:double">0.5</value>
          </InfoItem>
        </MetaData>
        <value>50.5</value>
      </InfoItem>
      <Object>
          <id>Oven</id>
          <InfoItem name="Temperature">
              <MetaData>
                  <InfoItem name="Latency">
                      <value type="xs:double">2.3</value>
                  </InfoItem>
                  <InfoItem name="Accuracy">
                      <value type="xs:double">0.05</value>
                  </InfoItem>
              </MetaData>
              <value>22.3</value>
          </InfoItem>
          <InfoItem name="Consumption">
              <MetaData>
                  <InfoItem name="Latency">
                      <value type="xs:double">2.3</value>
                  </InfoItem>
                  <InfoItem name="Accuracy">
                      <value type="xs:double">0.5</value>
                  </InfoItem>
              </MetaData>
              <value>50.5</value>
          </InfoItem>
      </Object>
    </Object>
    <Object>
      <id>BedRoom</id>
      <InfoItem name="Temperature">
        <MetaData>
          <InfoItem name="Latency">
            <value type="xs:double">2.3</value>
          </InfoItem>
          <InfoItem name="Accuracy">
            <value type="xs:double">0.05</value>
          </InfoItem>
        </MetaData>
        <value>22.3</value>
      </InfoItem>
      <InfoItem name="Moisture">
        <MetaData>
          <InfoItem name="Latency">
            <value type="xs:double">2.3</value>
          </InfoItem>
          <InfoItem name="Accuracy">
            <value type="xs:double">0.5</value>
          </InfoItem>
        </MetaData>
        <value>50.5</value>
      </InfoItem>
    </Object>
  </Object>
</Objects>

=== AaltoAsia/O-MI/O-MI Node/src/test/resources/parsing/odf_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns="odf.xsd" xs:schemaLocation="odf.xsd odf.xsd">
    <Object>
	<id>SmartHouse</id>
	<InfoItem name="PowerConsumption">
	    <value dateTime="2014-12-18T15:34:52">180</value>
	</InfoItem>
	<InfoItem name="Moisture">
	    <value unixTime="1418916892">0.20</value>
	</InfoItem>
	<Object>
	    <id>SmartFridge</id>
	    <InfoItem name="PowerConsumption">
		<value>56</value>
	    </InfoItem>
	</Object>
	<Object>
	    <id>SmartOven</id>
	    <InfoItem name="PowerOn">
		<value dateTime="2014-12-18T15:34:52">1</value>
	    </InfoItem>
	</Object>
    </Object>
    <Object>
	<id>SmartCar</id>
	<InfoItem name="Fuel">
	    <MetaData>
		<InfoItem name="Units">
		    <value type="xs:String">Litre</value>
		</InfoItem>
	    </MetaData>
	    <value dateTime="2014-12-18T15:34:52">30</value>
	</InfoItem>
    </Object>
    <Object>
	<id>SmartCottage</id>
	<Object>
	    <id>Heater</id>
	</Object>
	<Object>
	    <id>Sauna</id>
	</Object>
	<Object>
	    <id>Weather</id>
	</Object>
    </Object>
</Objects>
